name: 'Setup NuGet.exe for use with actions'
outbound-endpoints:
  - fqdn: dist.nuget.org
    port: 443
    reason: to download latest version of nuget
harden-runner-link: https://app.stepsecurity.io/github/Devils-Knight/Knowledge-base/actions/runs/1691501947 
